name: Deploy to github pages

# Run workflow on every push to the master branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy-to-github-pages:
  # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x

    - name: Install .NET WASM Build Tools
      run: dotnet workload install wasm-tools

    - name: Publish .NET project
      run: dotnet publish Server/Sz.Blazor.Reveal.Server.csproj -c:Release -p:GHPages=true -o dist/Web --nologo

    - name: List Files
      id: list-files
      uses: mirko-felice/list-files-action@v3.0.5
      with:
        repo: ${{ github.repository }}
        ref: ${{ github.ref }}
        path: dist

    - name: Replaces gh-pages branch via JamesIves github-pages-deploy-action
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        GITHUB_TOKEN: ${{ GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist/Web/wwwroot

    permissions:
      contents: write
