name: Deploy to github pages

# Run workflow on every push to the master branch
on:
  push:
    branches:
      - master
      - rendermode
  pull_request:
    branches:
      - master

jobs:
  deploy-to-github-pages:
  # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install .NET WASM Build Tools
      run: dotnet workload install wasm-tools

    - name: Publish .NET project
      run: dotnet publish Server/Sz.Blazor.Reveal.Server.csproj -c:Debug -p:GHPages=true -o dist/web --nologo

    - name: Change base-tag in index.html from / so GH Pages can run it in a virtual subdirectory
      run: sed -i 's|<base href="/"|<base href="/Sz.Blazor.Reveal/"|g' dist/web/wwwroot/index.html

    - name: Replaces gh-pages branch via JamesIves github-pages-deploy-action
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: dist/web/wwwroot
        token: ${{ secrets.ACCESS_TOKEN }}

    permissions:
      contents: write